from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import datetime


# ---------------------------------
# FOOD DONATION SCHEMAS & AI ALIGNMENT
# ---------------------------------
class FoodDonationCreate(BaseModel):
    title: str
    description: Optional[str] = None

    # Strict alignment for the AI Model
    quantity: float = Field(..., gt=0, description="Quantity of food in KG")
    unit: str = "kg"
    is_perishable: int = Field(
        ..., ge=0, le=1, description="1 if perishable, 0 if shelf-stable"
    )

    prepared_at: datetime
    expiry_at: datetime
    pickup_lat: float
    pickup_lng: float


class FoodDonationResponse(BaseModel):
    id: str
    donor_id: str
    donor_name: Optional[str] = None
    title: str
    description: Optional[str] = None
    quantity: float
    unit: str
    is_perishable: int
    prepared_at: datetime
    expiry_at: datetime
    pickup_lat: float
    pickup_lng: float
    urgency_score: float  # <--- Generated by the AI
    status: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class FoodDonationOwnerResponse(FoodDonationResponse):
    """Same as FoodDonationResponse, plus the secret pickup_code -- only
    ever returned to the donor who owns the donation, never to browsing
    NGOs/volunteers, since it's what the QR code / check-in flow relies
    on to prove someone was physically at the pickup location."""

    pickup_code: Optional[str] = None


class CompletePickupRequest(BaseModel):
    pickup_code: str = Field(..., min_length=1, max_length=10)


# ---------------------------------
# USER AUTHENTICATION SCHEMAS
# ---------------------------------
class UserCreate(BaseModel):
    full_name: str
    email: str
    password: str
    role: str  # e.g., 'donor', 'ngo', 'volunteer'
    phone_number: str


class UserLogin(BaseModel):
    email: str
    password: str


class UserResponse(BaseModel):
    id: str
    full_name: str
    email: str
    role: str
    phone_number: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    points: int = 0

    model_config = ConfigDict(from_attributes=True)


class LocationUpdate(BaseModel):
    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)


class ClaimResponse(BaseModel):
    id: str
    donation_id: str
    claimed_by_user_id: str
    status: str
    claimed_at: datetime

    class Config:
        from_attributes = True


class ClaimWithDonationResponse(ClaimResponse):
    """my-claims uses this so the dashboard doesn't need a second
    round-trip per claim to know what it's actually a claim for."""

    donation_title: Optional[str] = None
    donation_status: Optional[str] = None
    donation_quantity: Optional[float] = None
    donation_unit: Optional[str] = None
    pickup_lat: Optional[float] = None
    pickup_lng: Optional[float] = None


# ---------------------------------
# AI SCHEMAS: Smart Matching, Routing, Impact, Gamification
# ---------------------------------
class MatchCandidateResponse(BaseModel):
    user_id: str
    full_name: str
    role: str
    distance_km: float
    eta_minutes: float
    reliability_score: float
    match_score: float


class RouteStopResponse(BaseModel):
    donation_id: str
    title: str
    lat: float
    lng: float
    leg_distance_km: float
    leg_eta_minutes: float


class RouteResponse(BaseModel):
    stops: list[RouteStopResponse]
    total_distance_km: float
    total_eta_minutes: float


class ImpactResponse(BaseModel):
    total_donations_completed: int
    total_kg_saved: float
    meals_saved: int
    co2_kg_avoided: float
    active_donors: int
    active_recipients: int


class LeaderboardEntryResponse(BaseModel):
    user_id: str
    full_name: str
    role: str
    points: int
    badge: str
    completed_pickups: int
