from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import datetime

# ---------------------------------
# FOOD DONATION SCHEMAS & AI ALIGNMENT
# ---------------------------------
class FoodDonationCreate(BaseModel):
    title: str
    description: Optional[str] = None
    
    # Strict alignment for the AI Model
    quantity: float = Field(..., gt=0, description="Quantity of food in KG")
    unit: str = "kg"
    is_perishable: int = Field(..., ge=0, le=1, description="1 if perishable, 0 if shelf-stable")
    
    prepared_at: datetime
    expiry_at: datetime
    pickup_lat: float
    pickup_lng: float

class FoodDonationResponse(BaseModel):
    id: str
    donor_id: str
    title: str
    quantity: float
    unit: str
    expiry_at: datetime
    urgency_score: float  # <--- Generated by the AI
    status: str
    
    model_config = ConfigDict(from_attributes=True)